global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'order-service'
    static_configs:
    - targets: ['192.168.0.1:3000']
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  